services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_METHODS=${CORS_METHODS}
      - CORS_HEADERS=${CORS_HEADERS}
      - CORS_EXPOSE_HEADERS=${CORS_EXPOSE_HEADERS}
      - CORS_SUPPORTS_CREDENTIALS=${CORS_SUPPORTS_CREDENTIALS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
